data_cfg:
  dataset_name: CASIA-B
  dataset_root: your_data_path
  dataset_partition: ./datasets/CASIA-B/CASIA-B.json
  data_in_use: [true, true]
  num_workers: 1
  remove_no_gallery: false # Remove probe if no gallery for it
  test_dataset_name: CASIA-B

evaluator_cfg:
  enable_float16: true
  restore_ckpt_strict: true
  restore_hint: 50000
  save_name: TriGait
  sampler:
    batch_shuffle: false
    batch_size: 4
    sample_type: all_ordered # all indicates whole sequence used to test, while ordered means input sequence by its natural order; Other options:   fixed_unordered
    frames_all_limit: 720 # limit the number of sampled frames to prevent out of memory
  metric: euc # cos euc
  transform:
    - type: BaseSilCuttingTransform
    - type: Compose
      trf_cfg:
        - type: Reshape
        - type: PointNoise
        - type: JointNoise
        - type: MirrorPose
        - type: MultiInput
          if_OU: false

loss_cfg:
  - loss_term_weight: 1.0
    margin: 0.2
    type: TripletLoss
    log_prefix: triplet
  - loss_term_weight: 1.0
    scale: 16
    type: CrossEntropyLoss
    log_prefix: softmax
    log_accuracy: true

model_cfg:
  model: TriGait #TriGait_Gait3D_2dbackbone # # #TriGait_Gait3D_2dbackbone_woTS
  backbone_cfg:
  channels: # Layers configuration for automatically model construction
    - 32
    - 64
    - 128
    - 256
  class_num: 74
  hidden_dim: 256
  bin_num:
    - 64
  pos_cfg:
    in_channels:
      - 10
      - 64
      - 128
      - 256
    head: [ 0,1,2,3,4 ]
    shoulder: [ 5,6 ]
    elbow: [ 7,8 ]
    wrist: [ 9,10 ]
    hip: [ 11,12 ]
    knee: [ 13,14 ]
    ankle: [ 15,16 ]
    if_ou: false
  SeparateFCs:
    in_channels: 768
    out_channels: 256
    parts_num: 71
  SeparateBNNecks:
    class_num: 74
    in_channels: 256
    parts_num: 71
  Dataset: CASIA-B


optimizer_cfg:
  lr: 0.1
  momentum: 0.9
  solver: SGD
  weight_decay: 0.0005

scheduler_cfg:
  gamma: 0.1
  milestones: # Learning Rate Reduction at each milestones
    - 20000
    - 40000
    - 60000
  scheduler: MultiStepLR


trainer_cfg:
  enable_float16: true # half_percesion float for memory reduction and speedup
  fix_BN: false
  log_iter: 100
  with_test: true
  restore_ckpt_strict: true
  restore_hint: 0
  save_iter: 10000
  save_name: TriGait
  sync_BN: true
  total_iter: 80000
  sampler:
    batch_shuffle: true
    batch_size:
      - 8 # TripletSampler, batch_size[0] indicates Number of Identity
      - 16 #                 batch_size[1] indicates Samples sequqnce for each Identity
    frames_num_fixed: 30 # fixed frames number for training
    frames_skip_num: 0  #在一段连续的序列中随机跳过若干帧
    sample_type: fixed_ordered # fixed control input frames number, unordered for controlling order of input tensor; Other options: unfixed_ordered or all_ordered
    type: TripletSampler
  transform:
    - type: BaseSilCuttingTransform
    - type: Compose
      trf_cfg:
        - type: Reshape
        - type: PointNoise
        - type: JointNoise
        - type: MirrorPose
        - type: MultiInput
          if_OU: false
